//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public string MaHoaDonBan { get; set; }
        public string MaDonHang { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<int> TongThanhTien { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
